### PR TITLE
Phase nuisance as "stretch"

### PR DESCRIPTION
**Pull request by a2ray**
Inverts for a phase stretch factor in log10, and plotting cleaned up. Much more reuse of functions.

### CODE REVIEW

**Comment by richardt94** [comment]
Not sure if I understand why we need to sample the nuisance phase in log space - is this to bias the prior towards smaller phase corrections (and does this also mean the nuisance phase can no longer be negative?)

**Comment by richardt94** [comment]
Would also be good if you could rebase the commits starting with [`6a3e4bb`](https://github.com/richardt94/SNMRForward.jl/pull/4/commits/6a3e4bbad5696e235caa31940411814f39daf35e) on top of the latest master using a `git cherry-pick` or similar, as everything prior to this was already merged with the last PR

**Comment by a2ray** [comment]
So if you look [here](https://github.com/richardt94/SNMRForward.jl/blob/b0815bcd833681f75630eedaddc6763b6e9e8ff0/scripts/SMRPI/SMRPI.jl#L71) at `phasemodif` the stretch is always +ve but the offset could make final modeled phase ‐ve. If the phase stretch has to be -ve we should rather do this to the data than the forward prediction I believe as it would mean a difference in the FT convention. Log because the phase modifications could be quite large, and easier to sample and better to stress on small modifications. 

You'll have to explain `cherry‐pick` to me!

**Comment by richardt94** [comment]
@a2ray I've done a rebase on top of master, please check that your stuff in the scripts still works as expected

**Comment by richardt94** [comment]
I think it makes sense to merge this for now, and revisit later if we hear more about other phase corrections from the instrument vendor.

**Pull request merged**
